### ISSUE TITLE
Docker build not working

### ISSUE THREAD

**Issue by anderspitman** [robertaboukhalil/biowasm#5]
Hey @robertaboukhalil, the Docker build isn't working for me. It says it's missing lzma. Before I went down the debugging rabbit hole, I just wanted check and see if you're regularly using Docker for building biowasm tools and would expect it to work?

**Comment by robertaboukhalil** [comment]
Hey @anderspitman! I am regularly using that Docker image and it should be installing the `lzma` libraries when you do `make samtools` or `make htslib` [here](https://github.com/robertaboukhalil/biowasm/blob/master/tools/htslib/compile.sh#L6).

How are you running the build?

**Comment by anderspitman** [comment]
Yeah I just tried it on another machine with the same results. Here are the exact steps I did:

```bash
TAG=1.39.1
docker pull robertaboukhalil/emsdk:$TAG

# This part I added because it seemed necessary
cd ~
mkdir wasm
cd wasm
git clone https://github.com/robertaboukhalil/biowasm/issues/5

docker run \
    -dt \
    -p 12345:80 \
    --name wasm \
    --volume ~/wasm:/src \
    robertaboukhalil/emsdk:$TAG

docker exec -it wasm bash

cd biowasm/
make samtools
```

Here's the error:

```
cram/cram_io.c:57:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^~~~~~~~
1 error generated.
```
I'll start digging around on my end as well to see if I can figure it out.

**Comment by anderspitman** [comment]
Ok, so if I run `make htslib` first, then `make samtools` seems to work. I think the problem is that just running `make samtools` isn't actually installing the packages on my system. Just from glancing through the Makefile I don't see any obvious reason why that would be. Since I have it basically working, I'll wait to see if you have any ideas before doing further debugging.

**Comment by anderspitman** [comment]
Oh shoot I just noticed that the samtools readme (https://github.com/robertaboukhalil/biowasm/blob/master/tools/samtools/README.md) says to run make htslib before running make samtools.

**Comment by robertaboukhalil** [comment]
Ah I see, that would do it! I thought I had added a check [here](https://github.com/robertaboukhalil/biowasm/blob/master/tools/samtools/compile.sh#L5) but it must not be working properly

**Comment by anderspitman** [comment]
Thanks for the help. Hoping to have samtools up and running soon in a new little iobio app I'm working on.

**Comment by robertaboukhalil** [comment]
Awesome, looking forward to it!
